### ISSUE TITLE
Suggestion: sort updates in reverse chronological order

### ISSUE THREAD

**Issue by zachberger** [ritstudentgovernment/petitions#46] opened 2015-02-05 20:15 UTC

**Comment by Undeterminant** [comment] 2015-02-06 23:07
Duplicate of #21.

**Comment by petermikitsh** [comment] 2015-02-21 15:46
Did you mean sorted updates on the petition detail page (ex: https://pawprints.rit.edu/petitions/8Zh9F662rooLKjd6n) or the in progress page (https://pawprints.rit.edu/petitions/in-progress)?

**Closed** 2015-11-20 04:42 UTC
Labels: UI/UX, wontfix
