### ISSUE TITLE
Search doesn't return responded issues

### ISSUE THREAD

**Issue by ceko** [ritstudentgovernment/petitions#118] opened 2016-03-24 13:45 UTC
Is this by design?  For example, go to https://pawprints.rit.edu/petitions/xomY3GW43Q9D5igNQ with the title of Earlier Creative Industry Day.  If you search for that on https://pawprints.rit.edu/search it doesn't show up.

**Comment by NathanCastle** [comment] 2016-03-24 14:04
Good catch. I don't think that's by design and it is definitely new behavior. Will need to investigate to find a fix.

**Comment by ceko** [comment] 2016-03-24 14:14
I probably caused it by switching to the new search box, at least on my local copy I did.

**Comment by NathanCastle** [comment] 2016-04-05 18:32
Should be resolved in 097b332d4c51781b653b0dbe454cb328649b45a0

**Comment by NathanCastle** [comment] 2016-04-05 21:45
This is resolved and in master.

**Closed by NathanCastle** 2016-04-05 21:45 UTC
Labels: bug, in progress
